---
- name: Update all packages
  dnf:
    name: "*"
    state: latest

- name: Install OpenSCAP scanner and SCAP security guide
  dnf:
    name:
      - openscap-scanner
      - scap-security-guide
    state: present

- name: Copy the OpenSCAP scan script
  template:
    src: openscap_scan.sh.j2
    dest: /usr/local/bin/openscap_scan.sh
    mode: '0755'
  
- name: Create scap_reports directory
  shell: test -d /home/scap_reports || mkdir /home/scap_reports

- name: Copy server.py script
  template:
    src: server.py.j2
    dest: "{{ openscap_output_dir }}/server.py"

- name: Ensure the cron job is present for OpenSCAP scanning
  cron:
    name: "OpenSCAP Scan"
    job: "/usr/local/bin/openscap_scan.sh > /var/log/openscap_scan.log 2>&1"
    hour: "{{ openscap_cron_hour }}"
    minute: "{{ openscap_cron_minute }}"
    day: "{{ openscap_cron_day }}"
    month: "{{ openscap_cron_month }}"
    weekday: "{{ openscap_cron_weekday }}"

- name: Allow only necessary firewall ports
  firewalld:
    port: "{{ item.port }}"
    permanent: true
    state: enabled
  with_items:
    - { port: "22/tcp" }
    - { port: "8000/tcp" }  # To locally host reports.html
  when: firewall_enabled | default(true)

- name: Set default zone to drop
  firewalld:
    zone: public
    state: present
    permanent: true
    target: DROP

- name: Ensure specific allowed services
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
  loop:
    - ssh
    - http

- name: Ensure default drop for all other incoming traffic not explicitly allowed
  firewalld:
    rich_rule: 'rule family="ipv4" source not address="0.0.0.0/0" port port="22" protocol="tcp" accept'
    zone: public
    permanent: true
    state: enabled
    immediate: yes

  
- name: Reload firewalld to apply changes
  ansible.builtin.command: firewall-cmd --reload

- name: Harden SSH Configuration
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    # - { regexp: "^PermitRootLogin", line: "PermitRootLogin yes" }
    # - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
    - { regexp: "^X11Forwarding", line: "X11Forwarding no" }
    - { regexp: "^MaxAuthTries", line: "MaxAuthTries 3" }
  notify: Restart sshd

- name: Configure rsyslog for enhanced SSH logging
  lineinfile:
    path: /etc/rsyslog.conf
    line: 'authpriv.*                                              /var/log/secure'
  notify: Restart rsyslog

- name: Run the scan for the first time without verbose output
  command: "/usr/local/bin/openscap_scan.sh"
  ignore_errors: yes  # Does not return zero which is why it will show as an error, can be ignored

