---
- name: Install OpenSCAP scanner and SCAP security guide
  dnf:
    name:
      - openscap-scanner
      - scap-security-guide
    state: present

- name: Copy the OpenSCAP scan script
  template:
    src: openscap_scan.sh.j2
    dest: /usr/local/bin/openscap_scan.sh
    mode: '0755'
  
- name: Create scap_reports directory
  ansible.builtin.file:
    path: "{{ openscap_output_dir }}"
    state: directory
    mode: '0755'

- name: Run the scan for the first time without verbose output
  command: "/usr/local/bin/openscap_scan.sh"
  ignore_errors: yes  # Does not return zero which is why it will show as an error, can be ignored

