---
- name: Setup OpenSCAP
  hosts: "{{ host }}"
  become: true
  vars_files:
    - ../vars/main.yml
  roles:
    - package_management
    - openscap
    - flask_server
    - cron_management
    - security_hardening
